### ISSUE TITLE
please change the `latest` dist-tag to 0.3.5

### ISSUE THREAD

**Issue by miserylee** [jridgewell/sourcemaps#11]
please change the `latest` dist-tag to 0.3.5

currently retrieve the version is 0.3.6(which already deprecated)

```
npm show @jridgewell/gen-mapping version
0.3.6
```

**Comment by richardwei195** [comment]
+1

**Comment by Thanh-Long-Vu** [comment]
i am watting fix

**Comment by fengyon** [comment]
+1

**Comment by miserylee** [comment]
fixed in 0.3.7

**Comment by sanjay628** [comment]
Can you please publish new version with fixes ?

**Comment by jridgewell** [comment]
Thank you for the suggestion, I'm going to set the latest back to 0.3.5 since 0.3.7 is causing errors in old node versions.
