### ISSUE TITLE
Getting from next js for @jridgewell/gen-mapping/dist/gen-mapping.umd.js

### ISSUE THREAD

**Issue by Apatil15** [jridgewell/sourcemaps#13]
I am using next js 9.1.1
[BABEL] /app/node_modules/next/dist/client/next.js: Cannot find module '/app/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js', as per latest version its not working anymore, please help

**Comment by jridgewell** [comment]
v0.3.7 is published now.
