### ISSUE TITLE
@jridgewell/gen-mapping 0.3.7 error

### ISSUE THREAD

**Issue by chuxin-cs** [jridgewell/sourcemaps#19]
![image](https://github.com/user-attachments/assets/5d21a7fa-8ab1-4bcb-8b50-923bfe169191)

yarn install 0.3.7 error
@jridgewell/gen-mapping 0.3.7 error

**Comment by jridgewell** [comment]
Duplicate of https://github.com/jridgewell/sourcemaps/issues/14

**Comment by chuxin-cs** [comment]
@Jridgewell/gen mapping is being used by @ vue/cli plugin babel and cannot be downgraded
