### ISSUE TITLE
@jridgewell/gen-mapping  SyntaxError: Unexpected toke

### ISSUE THREAD

**Issue by arjunadobe** [jridgewell/sourcemaps#20]
Getting this error,

Previously i got the module missing error. That was solved. Now getting this error

   W: /app/.nvm/versions/node/v10.24.1/lib/node_modules/magepack/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js:1328

    W:             const originalLine = originalSource[sourceLine] ||= [];

    W: SyntaxError: Unexpected token =

    W:     at Module._compile (internal/modules/cjs/loader.js:723:23)

    W:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

    W:     at Module.load (internal/modules/cjs/loader.js:653:32)

    W:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

    W:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

    W:     at Module.require (internal/modules/cjs/loader.js:692:17)

    W:     at require (internal/modules/cjs/helpers.js:25:18)

    W:     at Object.<anonymous> (/app/.nvm/versions/node/v10.24.1/lib/node_modules/magepack/node_modules/@jridgewell/source-map/dist/source-map.cjs:6:18)

    W:     at Module._compile (internal/modules/cjs/loader.js:778:30)

    W:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by xiaoyaoting** [comment]
me too，Cannot find module error when using gen-mapping.umd.js

**Comment by AlanSean** [comment]
"overrides": {
    "@jridgewell/gen-mapping": "0.3.5"
  }

**Comment by knobel-dk** [comment]
Me too. I am getting this (only only using the lib a dependency to `@babel/generator``

```
#35 [frontend 19/19] RUN npm run build-only
#35 0.637 
#35 0.637 > ***@0.0.0 build-only
#35 0.637 > vite build
#35 0.637 
#35 1.363 failed to load config from /home/node/app/vite.config.ts
#35 1.364 error during build:
#35 1.364 Error: Cannot find module '/home/node/app/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
#35 1.364     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1070:15)
#35 1.364     at finalizeEsmResolution (node:internal/modules/cjs/loader:1063:15)
#35 1.364     at resolveExports (node:internal/modules/cjs/loader:547:14)
#35 1.364     at Module._findPath (node:internal/modules/cjs/loader:621:31)
#35 1.364     at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
#35 1.364     at Module._load (node:internal/modules/cjs/loader:901:27)
#35 1.364     at Module.require (node:internal/modules/cjs/loader:1115:19)
#35 1.364     at require (node:internal/modules/helpers:119:18)
#35 1.364     at Object.<anonymous> (/home/node/app/node_modules/@babel/generator/lib/source-map.js:7:19)
#35 1.364     at Module._compile (node:internal/modules/cjs/loader:1233:14)
```
