### ISSUE TITLE
still facing solved issue

### ISSUE THREAD

**Issue by lavkumarsinh** [jridgewell/sourcemaps#22]
Error: Cannot find module '/app/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'

**Comment by caojiawenn** [comment]
so am i.

**Comment by expdalex** [comment]
Me too, in version 0.3.7 this error remains.

**Comment by MicErmakov** [comment]
Issue faced to me. First occurrence near 3 hours ago.

**Comment by wanzicong** [comment]
![image](https://github.com/user-attachments/assets/6985bd6e-86a5-40be-8665-1d2756b0ced2)
me too， this is our program，s version ， i cannt build it successfully

**Comment by mcsigma** [comment]
Getting same issue

**Comment by stanekpa** [comment]
Published version gen-mapping 0.3.7 is bad:_

\@jridgewell\gen-mapping\dist\gen-mapping.umd.js:1328
            const originalLine = originalSource[sourceLine] ||= [];

**Comment by stanekpa** [comment]
> Try downgrading to version **0.3.5** using the following code in your **package.json**:
> 
> ```
> "resolutions":{
>    "@jridgewell/gen-mapping":"0.3.5",
> }
> ```

This solution works for one project, but we have multiple projects with multiple branches and it is not possible to fix it this way :(
