### ISSUE TITLE
No `dist` directory on `@jridgewell/gen-mapping` (0.3.6)

### ISSUE THREAD

**Issue by samchon** [jridgewell/sourcemaps#3]
https://www.npmjs.com/package/@jridgewell/gen-mapping?activeTab=code

Looking at distributed package of `@jridgewell/gen-mapping`, no `dist` directory found.

**Comment by nealol** [comment]
Also running into this issue as of 0.3.6

**Comment by vitor3g** [comment]
same here

**Comment by jridgewell** [comment]
I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`
