### ISSUE TITLE
Last published version of `@jridgewell/gen-mapping` (0.3.6) doesn't have `dist` folder

### ISSUE THREAD

**Issue by artemdemo** [jridgewell/sourcemaps#4]
Hi guys,

Last published version of `@jridgewell/gen-mapping` (0.3.6) doesn't have `dist` folder.

Which means it's broken 😞 because [package.json assumes `dist` is there](https://github.com/jridgewell/sourcemaps/blob/08ff6d74bfb0dd798011c4f29646ee80d99d1ebf/packages/gen-mapping/package.json#L18-L25)

**Comment by jridgewell** [comment]
I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`
