### ISSUE TITLE
The latest version 0.3.6 does not have a dist directory, so it is speculated that there was no build processing before its release

### ISSUE THREAD

**Issue by wibetter** [jridgewell/sourcemaps#5]
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/f6b901f0-033a-4191-9a0a-c94df242a94d"><img width="836" alt="image" src="https://github.com/user-attachments/assets/3144d06e-f2d0-4b99-81c9-9e0bd9b17b50">

**Comment by CaoMeng** [comment]
Same issue. Help~

**Comment by darrenplace** [comment]
this is breaking babel-loader :(

**Comment by Jacobtims** [comment]
Same here on a Laravel project

**Comment by wibetter** [comment]
Temporary solution to version 0.3.6 issue
http://github.com/jridgewell/sourcemaps/issues/6

**Comment by PiyushAgrawal1243** [comment]
Same issue.

**Comment by jridgewell** [comment]
I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`
