### ISSUE TITLE
Temporary solution to version 0.3.6 issue

### ISSUE THREAD

**Issue by wibetter** [jridgewell/sourcemaps#6]
Manually add the dependency @ jridgewell/gen mapping in the project and lock version 0.3.5.
<img width="714" alt="image" src="https://github.com/user-attachments/assets/2a2a0f8e-e0ff-46e0-ab5b-7b43544961f0">

**Comment by zetavg** [comment]
What I do is adding

```
  "resolutions": {
    "@jridgewell/gen-mapping": "0.3.5"
  }
```

to `package.json` while using yarn as the package manager, and it seems that adding to dependencies does not work for me since there's `node_modules/@babel/generator/node_modules/@jridgewell/gen-mapping` which will still be 0.3.6.

**Comment by LouisHaftmann** [comment]
for pnpm in `package.json`

```
{
  "pnpm": {
    "overrides": {
      "@jridgewell/gen-mapping": "0.3.5"
    }
  }
}
```

**Comment by Hao-yiwen** [comment]
same question, please fix it.

**Comment by ikeq** [comment]
same here, please fix ASAP 😖.

**Comment by tiwarishubham635** [comment]
Facing same issue

**Comment by Arweil** [comment]
The build product does not have a dist directory

<img width="836" alt="image" src="https://github.com/user-attachments/assets/bcd06629-53f8-4a28-ad15-5af13004fe7d">
<img width="862" alt="image" src="https://github.com/user-attachments/assets/2f4d5bc3-1c47-43ac-8d32-247316fbfdcc">

**Comment by stanekpa** [comment]
Please fix ASAP

**Comment by jridgewell** [comment]
I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`

**Comment by mirari** [comment]
Same problem. Currently using the override config or uploading the lock file is the only way to fix it.

**Comment by ikeq** [comment]
> I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`

<img width="804" alt="image" src="https://github.com/user-attachments/assets/ce417f66-6ad0-4567-8f08-df49d6344cb0">
Can still get 0.3.6 version 😖

**Comment by stanekpa** [comment]
Package 0.3.6 is still on https://www.npmjs.com/

**Comment by vladimirivanoviliev** [comment]
FYI In my case simple npm install did't fix the issue, instead I need to clean up my global packages and npm cache as well.
