### ISSUE TITLE
Missing dist in the v0.3.6 gen-mapping

### ISSUE THREAD

**Issue by gireeshamg** [jridgewell/sourcemaps#7]
Missing dist folder in the gen-mapping v0.3.6 when installed using pnpm. 

Its available in 0.3.5 
<img width="407" alt="Screenshot 2024-12-10 at 1 28 43 PM" src="https://github.com/user-attachments/assets/d4c13182-47ec-49ea-b830-d2e5e55a9116">

**Comment by tyrann0us** [comment]
Duplicate of #5, workaround in #6.

**Comment by jridgewell** [comment]
I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`

**Comment by zadzbw** [comment]
> I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`

@jridgewell maybe we should publish a new version just like `0.3.7` without the issue instead of unpublish `0.3.6`?

**Comment by SSzzPP** [comment]
You can roll back to version 0.3.5 because the directory structure has changed in 0.3.6. like `"@jridgewell/gen-mapping": "0.3.5"`

**Comment by anoopsivasankaran** [comment]
Im still getting the error. Even after removing the package-lock and node_modules

**Comment by out-dev** [comment]
But problems with third-party dependencies will stay?

**Comment by fengmk2** [comment]
should set the npm latest to 0.3.5

**Comment by valera33** [comment]
this is why I got it :) and yes still getting `0.3.6` even after `npm cache clean`
```
└─┬ @angular-devkit/build-angular@0.1102.19
  └─┬ @babel/core@7.12.10
    └─┬ @babel/traverse@7.26.4
      └─┬ @babel/generator@7.26.3
        └── @jridgewell/gen-mapping@0.3.6
```

**Comment by SSzzPP** [comment]
You just need to specify the version in package.json, like `"@jridgewell/gen-mapping": "0.3.5"`

**Comment by inzanez** [comment]
I do not really see that this is the way to move forward if this is not a package that I need in my project but it is brought in by a dependency?...

**Comment by jridgewell** [comment]
v0.3.7 is published.
