### ISSUE TITLE
Getting build error After latest 0.3.6 release. Cant find module Cannot find module gen-mapping.umd.js

### ISSUE THREAD

**Issue by anoopsivasankaran** [jridgewell/sourcemaps#9]
Getting react project build error after 0.3.6 release. 
All working good so far. no code change. Build failed from github action. 

```
Error:  Cannot find module '/project-tracker/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'

**Comment by fitzlf** [comment]
me too..

**Comment by xuyakai11** [comment]
Cannot find module node_modules/.pnpm/@ampproject+remapping@2.3.0/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs

**Comment by hurkanugur** [comment]
Same

**Comment by aikenahac** [comment]
The broken version was unpublished, see #7

**Comment by SSzzPP** [comment]
You can roll back to version 0.3.5 because the directory structure has changed in 0.3.6

**Comment by zadzbw** [comment]
@jridgewell maybe we should publish a new version just like `0.3.7` without issue instead of unpublish `0.3.6`?

**Comment by zhulduz** [comment]
**expo** project from the scratch: `Error: Cannot find module '.../node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'`

**Comment by inzanez** [comment]
Hm...on my end it does not rollback, for whatever reason. Cache cleared etc. but I still get the version 0.3.6...

**Comment by NagarjunShroff** [comment]
Same issue : Error: Cannot find module '.../node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'

**Comment by SSzzPP** [comment]
`"@jridgewell/gen-mapping": "0.3.5"` is OK, But it would be better to release `0.3.7`

**Comment by jridgewell** [comment]
I unpublished the broken version. Please rerun your package manager to pick up the previous `v0.3.5`

**Comment by anikettraya** [comment]
Same issue.

`[Error: Cannot find module '/bp/workspace/traya_crm_v3/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js']`

**Comment by NagarjunShroff** [comment]
> `"@jridgewell/gen-mapping": "0.3.5"` is OK, But it would be better to release `0.3.7`

I tried with 0.3.5 - didn't work

**Comment by lesongvi** [comment]
Same issue:
```
Error: [BABEL]: Cannot find module '/app/node_modules/@babel/generator/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
```

**Comment by maheshwa35** [comment]
Need to rollback to 0.3.5 version.

**Comment by inzanez** [comment]
That does not work,...

**Comment by SSzzPP** [comment]
> > `"@jridgewell/gen-mapping": "0.3.5"` is OK, But it would be better to release `0.3.7`
> 
> I tried with 0.3.5 - didn't work

delete package.lock and node_modules, re-run install

**Comment by inzanez** [comment]
I did that..
```
rm -rf node_modules
rm package-lock.json
npm cache clean --force
npm install
```
Result being:
```
...
npm warn deprecated @jridgewell/gen-mapping@0.3.6: publish failed to build the dist directory
---
```

**Comment by sergioh-imascono** [comment]
The “npm warn deprecated @jridgewell/gen-mapping@0.3.6: publish failed to build the dist directory” message is still displayed.

**Comment by Tamas-hi** [comment]
Yeah, it seems that unpublishing doesnt solve this issue. I am still getting the 0.3.6 and therefore the errors (even after deleting package-lock, node_modules, my pnpm store)

**Comment by SSzzPP** [comment]
You may need to specify the version in package.json, for example "@jridgewell/gen-mapping": "0.3.5"

**Comment by anoopsivasankaran** [comment]
Im not using this package directly. I use it through babel core for react. Removed the package lock and node modules. But still getting the error

**Comment by petervanstark** [comment]
Way to many dependencies for this one, this would require many many changes to many packages.

**Pls rollback to 0.3.5 via publish as new version 0.3.7 so latest is good.**

E.g. babel. Remember xkcd post?

**Comment by sergioh-imascono** [comment]
> Im not using this package directly. I use it through babel core for react. Removed the package lock and node modules. But still getting the error

Same here

**Comment by inzanez** [comment]
@SSzzPP it is a package from a dependency,...that cannot be the intended way to fix this. Sounds pretty unusual.

**Comment by hurkanugur** [comment]
**If you're not directly using this dependency:**

1. Open `package-lock.json`.  
2. Replace all occurrences of **`"gen-mapping": "^0.3.5"`** with **`"gen-mapping": "0.3.5"`**.

**Comment by anoopsivasankaran** [comment]
> **If you're not directly using this dependency:**
> 
> 1. Open `package-lock.json`.
> 2. Replace all occurrences of **`"gen-mapping": "^0.3.5"`** with **`"gen-mapping": "0.3.5"`**.

Wont help Coz it runs on github action too

**Comment by inzanez** [comment]
@hurkanugur yeah, that is nice to get my project building manually,...but that is not something that works with automated workflows, is it?

**Comment by hurkanugur** [comment]
I just suggested this to save the day for now (temp solution) @inzanez

**Comment by dpraczuk** [comment]
@jridgewell Can u please read comments above? Babel-core is using ur dependency, and it's impossible to rollback in most cases. New version will do the work I guess

**Comment by Rouret** [comment]
use @dpraczuk it's work

> "overrides": {
>       "@jridgewell/gen-mapping": "0.3.5"
>     }

**Comment by Autrikektor** [comment]
Очень пригорело, спасибо

**Comment by inzanez** [comment]
@hurkanugur which is nice. But people do have to realize that in most cases this rollback-suggestion is not working. As many of us depend on automation; which means: please publish a fix version 0.3.7...so that things work normally again.

**Comment by ondrej-langr** [comment]
@jridgewell Dude, just publish new version. Unpublishing or even deleting the version does nothing. There are still dependants on your package so NPM wont stop them from downloading it. Publishing fresh new version should solve the issue.

If you wanted to test your new migration to monorepo you could use prereleases...

**Comment by hurkanugur** [comment]
@inzanez I mean I want that solution too, but it is not up to me lol

**Comment by jridgewell** [comment]
New v0.3.7 is published now.

> @jridgewell Dude, just publish new version. Unpublishing or even deleting the version does nothing. There are still dependants on your package so NPM wont stop them from downloading it. Publishing fresh new version should solve the issue for people not directly using your package but using it through babel.
> 
> If you wanted to test your new migration to monorepo you could use prereleases...

Buddy, I had to figure out why it wasn't building and fix the fucking problem first. It's 3am here.

**Comment by inzanez** [comment]
@jridgewell many thanks!!!

**Comment by ondrej-langr** [comment]
> New v0.3.7 is published now.
> 
> > @jridgewell Dude, just publish new version. Unpublishing or even deleting the version does nothing. There are still dependants on your package so NPM wont stop them from downloading it. Publishing fresh new version should solve the issue for people not directly using your package but using it through babel.
> > If you wanted to test your new migration to monorepo you could use prereleases...
> 
> Buddy, I had to figure out why it wasn't building and fix the fucking problem first. It's 3am here.

Thanks. Man I get it. But you have 50m weekly downloads on this project so its quite understandable that people are up on your arse. If you would like some help with this next time then I will gladly help.

**Comment by MaxLee1980** [comment]
@jridgewell Dude, When I upgrade version to 0.3.7 that A new problem has emerged：
my project use Angular 9 and node v14.15.0<
![image](https://github.com/user-attachments/assets/30d1ceff-806c-42fe-9e71-d6b29f6cb230)
function buildBySources(decoded, memos) {
        const sources = memos.map(buildNullArray);
        for (let i = 0; i < decoded.length; i++) {
          const line = decoded[i];
          for (let j = 0; j < line.length; j++) {
            const seg = line[j];
            if (seg.length === 1) continue;
            const sourceIndex2 = seg[SOURCES_INDEX2];
            const sourceLine = seg[SOURCE_LINE2];
            const sourceColumn = seg[SOURCE_COLUMN2];
            const originalSource = sources[sourceIndex2];
            const originalLine = originalSource[sourceLine] ||= [];
            const memo = memos[sourceIndex2];
            let index = upperBound(
              originalLine,
              sourceColumn,
              memoizedBinarySearch(originalLine, sourceColumn, memo, sourceLine)
            );
            memo.lastIndex = ++index;
            insert2(originalLine, index, [sourceColumn, i, seg[COLUMN2]]);
          }
        }
        return sources;
      }
     The error you're encountering is due to the use of the logical assignment operator (||=), which is a relatively new feature in JavaScript and may not be supported in all environments, particularly older versions of Node.js or browsers.
     how can I fixed it?

**Comment by namsic6460** [comment]
@MaxLee1980 Use this in package.json. It worked to me
"overrides": {
  "@jridgewell/gen-mapping": "0.3.5"
}

**Comment by jridgewell** [comment]
I've already reset the lastest version back to 0.3.5.

**Comment by namsic6460** [comment]
> I've already reset the latest version back to 0.3.5.

Anyway, it isn't working. Build still throws error

**Comment by MaxLee1980** [comment]
@jridgewell Thanks budy, It's working now.
@namsic6460 Hi, Dude, You can try this command: npm install @jridgewell/gen-mapping@0.3.5 --save-exact
This command will install version 0.3.5 of @jridgewell/gen-mapping and use the --save-exact flag to ensure that the exact version of this dependency is saved in the package.json file.

**Comment by namsic6460** [comment]
> @jridgewell Thanks budy, It's working now.
> @namsic6460 Hi, Dude, You can try this command: npm install @jridgewell/gen-mapping@0.3.5 --save-exact
> This command will install version 0.3.5 of @jridgewell/gen-mapping and use the --save-exact flag to ensure that the exact version of this dependency is saved in the package.json file.
> 

Don't install. just add to package.json

**Comment by MaxLee1980** [comment]
@namsic6460 Is it work now?

**Comment by namsic6460** [comment]
> @namsic6460 Is it work now?

After I add that statement, yes

**Comment by MaxLee1980** [comment]
@namsic6460 me too. Thanks budy.
